services:

    chunk.manager:
      class: ChunkTypeBundle\Util\ChunkManager
      arguments: [ @doctrine.orm.default_entity_manager ]

    chunk.form.type.widget:
      class: ChunkTypeBundle\Form\Type\ChunkWidgetType
      arguments: [ @chunk.manager, @request_stack ]
      tags:
        - { name: form.type, alias: chunk }